version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./front-end
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on: 
      - backend
    volumes: 
      - ./front-end/src:/app-frontend/src
      - ./front-end/package.json:/app-frontend/package.json
    environment:
      - REACT_APP_HOSTNAME=localhost
      - REACT_APP_BACKEND_PORT=3001
      - NODE_TLS_REJECT_UNAUTHORIZED=0
  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on: 
      db:
        condition: service_healthy
    volumes: 
      - ./back-end:/app-backend
    environment:
      - GO111MODULE=on
      - PROJECT_DIR=/back-end
      - CGO_ENABLED=0
      - PORT=3001
      - JWT_SECRET=jwt_secret
      - HOSTNAME=db
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=senhaDoDB
      - MYSQL_DB_NAME=app-recipes-db
  db:
    image: mysql:latest
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senhaDoDB
      - MYSQL_DATABASE=app-recipes-db
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    restart: 'always'
volumes:
  mysql-data:
