version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./front-end
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    volumes: 
      - ./front-end/src:/app-frontend/src
      - ./front-end/package.json:/app-frontend/package.json
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001
  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    volumes: 
      - ./back-end:/app-backend
    environment:
      - GO111MODULE=on
      - PROJECT_DIR=/back-end
      - CGO_ENABLED=0
      - PORT=3001
      - JWT_SECRET=jwt_secret
      - HOSTNAME=db
      - DB_CONNECTION_STRING=admin:senhaDoDB@tcp(db:3306)/app-recipes-db?charset=utf8mb4&parseTime=True&loc=Local
  db:
    image: mysql:latest
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senhaDoDB
      - MYSQL_DATABASE=app-recipes-db
    volumes:
      - mysql-data:/var/lib/mysql
    restart: 'always'
volumes:
  mysql-data:
